# Base URL of the site, the only required config argument - also used for sitemap and rss
base_url = "https://alphara.art"

# Used in RSS by default
title = "Alphara's Blog"
description = "Blog dedicated to my stuff"

# The default language, used in RSS and as a fallback value
default_language = "en"

# Theme name to use
# theme = ""

# Highlight all code blocks found
# Or enable the highlight.js in the 'extra' config section
highlight_code = true

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "base16-atelierdune-light" # "1337"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
           {name = "tags", rss = true}
]

# Whether to automatically compile all sass files found in the `sass` directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = false

# Whether to build a search index out of the pages and section
# content for the `default_language`
# or whether to build a search index to be used later on by a JavaScript library
build_search_index = true # false

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# Optional translation object. The key if present should be a language code
[translations]

# You can put any kind of data in there and it
# will be accessible in all templates
[extra]
# Put all your custom variables here

# MathJax rendering support
math = true

home_subtitle = "Some profound and catchy statement"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "twitter", link = "https://twitter.com" },
    { name = "github", link = "https://github.com" },
    { name = "email", link = "mailto:author@domain.com" }
]


# You can use highlight.js for code highlighting if you dont like the default one
[extra.highlightjs]

enable = true
clipboard = true
theme = "base16-atelierdune-light" # "railscasts"

[extra.disqus]

enable = false

# Take this from your Disqus account
shortname = "my-supa-dupa-blog"
# Cpmments can be disabled per page by setting:
# [extra]
# disable_comments = true
#
# in the posts front-matter

[extra.author]
name = "Iustin Râznic"
email = "iustin@alphara.art"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
