# Base URL of the site, the only required configuration variable - also used for sitemap and rss feed
base_url = "https://alphara.art"

# Used in RSS by default
title = "Alphara's Blog"
description = "Neural Art at its finest :))" # Blog dedicated to my stuff

# The default author for pages
author = "Iustin Râznic"

# The default language, used in RSS and as a fallback value
default_language = "en"

# The site theme to use.
# theme = ""

# Whether to automatically compile all sass files found in the `sass` directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# A list of glob patterns specifying asset files to ignore when processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# Similar to ignored_content, a list of glob patterns specifying asset files to
# ignore when the static directory is processed. Defaults to none, which means
# that all asset files are copied over to the `public` directory
ignored_static = []

# Whether to generate a RSS feed automatically
generate_feeds = true
feed_filenames = ["atom.xml"]

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       { name = "tags", rss = true }, # each tag will have its own RSS feed
#       { name = "categories", paginate_by = 5 },  # 5 items per page for a term
#       { name = "authors" } # Basic definition: no RSS or pagination
#     ]
taxonomies = [
    { name = "tags", rss = true }
]

[markdown]

# Highlight code blocks
highlight_code = true
#highlight_theme = "boron" # 100% best practice contrast for comments
highlight_theme = "ayu-dark" # 94%
#highlight_theme = "1337" # 94%

# Use emojis like :smile: and :shrug:
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isn’t ok
lazy_async_image = false

[extra]

home_subtitle = "Neural Art at its finest :))"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "github", link = "https://github.com/xAlpharax" },
    { name = "linkedin", link = "https://www.linkedin.com/in/iustin-raznic" },
    { name = "youtube", link = "https://www.youtube.com/@alphara2643" },
    { name = "twitter", link = "https://twitter.com/IustinRaznic" },
    { name = "email", link = "mailto:iustin@alphara.art" }
]

[extra.author]

name = "Iustin Râznic"
email = "iustin@alphara.art"

[extra.meta]

website_type = "blog" # either "blog" or "article" - I haven't seen any difference though

keywords = "blog, technology, science, philosophy, mathematics, artificial intelligence, AI research, machine learning, data science, deep learning, neural networks, Linux, Void Linux, OpenBSD, system administration, open source, FOSS, developer tools, programming, coding, tutorials, programming languages, software development, software engineering, computer science, algorithms, cybersecurity"

preview_image_src = "https://alphara.art/Alphara.png"
preview_image_alt = "Alphara"

twitter_card = "summary_large_image" # either "summary" or "summary_large_image" (for big preview image)

twitter_creator = "@IustinRaznic" # twitter handle of the author

[extra.disqus]

# enable = false

# Take this from your Disqus account
# shortname = "my-supa-dupa-blog"

# Make sure to include this on posts that you want comments on:
# [extra]
# permalink = "link of the page"
#
# in the posts front-matter
# in order to have the correct URL for the comment section

# Comments can be disabled per page by setting:
# [extra]
# disable_comments = true
#
# in the posts front-matter
# this will skip disqus components from rendering on the page all together


### PAGE SPECIFIC TOGGLES ###


# Table of Contents button-functionality can be enabled per-page by adding:
# [extra]
# toc=true
#
# in the page front-matter

# Similarily,

# Math Latex (KaTeX) rendering can be enabled per-page by adding:
# [extra]
# math=true
#
# in the page front-matter

# Similarily,

# Navigation buttons can be enabled per-page by adding:
# [extra.earlier]
# title = "Typography"
# permalink = "https://alphara.art/posts/typography"

# AND/OR (if needed)

# [extra.later]
# title = "Henlo Internet!"
# permalink = "https://alphara.art/posts/how-i-made-this-blog-with-zola/"

[extra.google_analytics]

# enable = false

# id = "UA-4XXXXXXX-X"
